CREATE TABLE IF NOT EXISTS Blogpost (
    id UNIQUEIDENTIFIER PRIMARY KEY,
    title NVARCHAR(255) NOT NULL,
    content NVARCHAR(MAX),
    created_by UNIQUEIDENTIFIER NOT NULL,
    created_at DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
    updated_at DATETIME2 NOT NULL DEFAULT GETUTCDATE(),

    CONSTRAINT FK_Blogpost_User FOREIGN KEY (created_by) REFERENCES [User](id)
)
