services:
  database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "oPax9HFmjU4AVAqXEeA"
      ACCEPT_EULA: "Y"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P 'oPax9HFmjU4AVAqXEeA' -C -d test -Q 'SELECT 1' || exit 1",
        ]
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 30s
    command: >
      /bin/bash -c "(/opt/mssql/bin/sqlservr) & sleep 10; /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P 'oPax9HFmjU4AVAqXEeA' -C -Q 'CREATE DATABASE test' & wait"
  migrate:
    image: "migrate/migrate"
    volumes:
      - "./../migrations:/migrations"
    command:
      - "-path=/migrations/"
      - "-database"
      - "sqlserver://sa:oPax9HFmjU4AVAqXEeA@database:1433?database=test&TrustServerCertificate=true"
      - "up"
    depends_on:
      database:
        condition: service_healthy
    restart: "no"
  backend:
    build:
      context: "./.."
      dockerfile: ".//build/api.Dockerfile"
    stop_signal: SIGINT
    environment:
      - TESTCONTAINERS_DB_DSN=sqlserver://sa:oPax9HFmjU4AVAqXEeA@database:1433?database=test&TrustServerCertificate=true
      - TESTCONTAINERS_DB_MAXOPENCONNS=256
      - TESTCONTAINERS_DB_MAXIDLECONNS=256
      - TESTCONTAINERS_DB_MACIDLETIME="15m"
      - TESTCONTAINERS_DB_TIMEOUT=30
    depends_on:
      database:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully
    ports:
      - "4000:4000"
    restart: "no"
